<Project>
  <PropertyGroup>
    <TvAIrProductVersion>1.2.0</TvAIrProductVersion>
    <TvAIrFileVersion>1.2.0.0</TvAIrFileVersion>
    <TvAIrAssemblyVersion>1.2.0.0</TvAIrAssemblyVersion>
    <TvAIrPluginSdkVersion>1.1.5</TvAIrPluginSdkVersion>
    <TvAIrPluginSdkAssemblyVersion>1.0.0.0</TvAIrPluginSdkAssemblyVersion>
    <TvAIrPluginHostContractVersion>1.1.5</TvAIrPluginHostContractVersion>
    <TvAIrPublicContractName>release_contract</TvAIrPublicContractName>
    <TvAIrPluginHostContractName>plugin-host-foundation</TvAIrPluginHostContractName>
    <TvAIrPluginCompatibilityMajor>1</TvAIrPluginCompatibilityMajor>
    <TvAIrMinimumSupportedPluginHostContractVersion>1.0.0</TvAIrMinimumSupportedPluginHostContractVersion>
  </PropertyGroup>
</Project>
